#!/bin/bash
source ./validator


clear
echo "Welcome to Pk global one click infrastructure setup"

echo "Please aselect the kind in infrastructure you want to setup"
echo ' 1. ONPREM'
echo ' 2. CLOUD'
read  -p 'Select the infrastructure : ' INFRA

case $INFRA in

  1 | onprem | ONPREM)
    clear
     echo "you have selected onprem as your Environment, Please wait while we check the dependencies"
            terraformPackage
	    onprem
            echo "Dependencies Validated Successfully"
            source ./CloudProviders/onprem
            onpremInit
    ;;

  2 | CLOUD | cloud)
        clear
	echo 'In which cloud you would like to setup the infra'
  echo '1. AWS'
	echo '2. AZURE'
	echo '3. Google'
	read -p 'Select cloud provider : ' PROVIDER
        case $PROVIDER in
  	  AWS | aws | 1)
            echo "you have selected AWS as your cloud provider, Please wait while we check the dependencies"
            terraformPackage
	    awsCloud
            echo "Dependencies Validated Successfully"
            source ./CloudProviders/aws
            awsInit
	  ;;
	  AZURE | azure | 2)
            terraformPackage
            azureCloud
            echo "Dependencies Validated Successfully"
            source ./CloudProviders/azure
            azureInit
	  ;;
	Google | google | 3)
            terraformPackage
            googleCloud
            echo "Dependencies Validated Successfully"
            source ./CloudProviders/google
            googleInit
	  ;;
          *)
          echo "Currently this provider is not supported"
	 ;;
       esac
    ;;

  *)
    echo "Input Unknown, Please select the correct input"
    ;;
esac
